name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install and Build
        run: |
          npm ci
          npm run build-ghpages

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}