name: Deploy
on: 
  push:
    paths:
      - 'public/**'
jobs:
   # Deployment job
   deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            publish_dir: ./public
            github_token: ${{ secrets.GITHUB_TOKEN }}
